### ISSUE TITLE
Moving Items outputs Numbers in Chat

### ISSUE THREAD

**Issue by Nanabell** [GoodPro712/ControlTrash#1]
Love the idea and the problem is not game breaking but gets somewhat annoying pretty quickly.
Every time i move an item in my inventory the chat outputs what i can only assume are debug numbers. It seems to be "-1" most of the time

**Comment by Metacinnabar** [comment]
My first Github isuue! The numbers in chat were some debugging code left behind and is fixed in v1.1. I will release this version very soon.

**Comment by Metacinnabar** [comment]
Version released, issue closed
